/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadImport } from './routes/upload'
import { Route as DreamsImport } from './routes/dreams'
import { Route as IndexImport } from './routes/index'
import { Route as EmailEmailIdImport } from './routes/email.$emailId'

// Create/Update Routes

const UploadRoute = UploadImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any)

const DreamsRoute = DreamsImport.update({
  id: '/dreams',
  path: '/dreams',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmailEmailIdRoute = EmailEmailIdImport.update({
  id: '/email/$emailId',
  path: '/email/$emailId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dreams': {
      id: '/dreams'
      path: '/dreams'
      fullPath: '/dreams'
      preLoaderRoute: typeof DreamsImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadImport
      parentRoute: typeof rootRoute
    }
    '/email/$emailId': {
      id: '/email/$emailId'
      path: '/email/$emailId'
      fullPath: '/email/$emailId'
      preLoaderRoute: typeof EmailEmailIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dreams': typeof DreamsRoute
  '/upload': typeof UploadRoute
  '/email/$emailId': typeof EmailEmailIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dreams': typeof DreamsRoute
  '/upload': typeof UploadRoute
  '/email/$emailId': typeof EmailEmailIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dreams': typeof DreamsRoute
  '/upload': typeof UploadRoute
  '/email/$emailId': typeof EmailEmailIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dreams' | '/upload' | '/email/$emailId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dreams' | '/upload' | '/email/$emailId'
  id: '__root__' | '/' | '/dreams' | '/upload' | '/email/$emailId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DreamsRoute: typeof DreamsRoute
  UploadRoute: typeof UploadRoute
  EmailEmailIdRoute: typeof EmailEmailIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DreamsRoute: DreamsRoute,
  UploadRoute: UploadRoute,
  EmailEmailIdRoute: EmailEmailIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dreams",
        "/upload",
        "/email/$emailId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dreams": {
      "filePath": "dreams.tsx"
    },
    "/upload": {
      "filePath": "upload.tsx"
    },
    "/email/$emailId": {
      "filePath": "email.$emailId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
